spring.application.name=event-management-qr
# App

server.port=8080

# MySQL Database (PERMANENT STORAGE)
spring.datasource.url=jdbc:mysql://localhost:3306/eventdbqr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Password@123

# JPA - update keeps data, never drops tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bujjiappanapalli@gmail.com
spring.mail.password=ssqhwieblfhtmdgk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true